### ISSUE TITLE
Autonomous TODO

### ISSUE THREAD

**Issue by Philanatidae** [FIRST-Team-2557-The-SOTABots/FRC_Robot#4]
These are the items that still need to be finished in order to finish autonomous.
- [x] Test robot driving straight
- [x] Implement distance drive using the encoders on the drive wheels
- [x] Test Low Bar autonomous with distance
- [x] Test Chival de Frise autonomous with distance
- [x] Test Portcullis autonomous with distance
- [x] Test Rough Terrain autonomous with distance
- [x] Test Rock Wall autonomous with distance
- [x] Test Ramparts autonomous with distance
- [x] Test Moat autonomous with distance
- [x] ~~Create an autonomous for shooting in the high goal as a spy-robot~~
- [ ] ~~Turn back straight after an auto is done (some of them rotate the robot off)~~
- [x] Add option to shoot/not shoot ball during auto
- [x] Add positions to different batters
- [x] Add turning to the target using vision
- [x] Add driving onto the batter and shooting
