### ISSUE TITLE
Vision TODO

### ISSUE THREAD

**Issue by Philanatidae** [FIRST-Team-2557-The-SOTABots/FRC_Robot#5]
These are the items that still need to be finished in order to finish vision.
- [x] Set the Pi's IP to a static 10.25.57.11
- [x] Set the RoboRIO's IP to a static 10.25.57.2 (subnet 255.255.255.0)
- [x] Modify current vision commands to use PIDs
- [x] Test vision tracking and determine offset from center of camera to line up the robot with the high goal
- [x] Add vision tracking to the end of all autonomous modes
- [x] Attach correction commands to the manipulator's gamepad
- [ ] Update the documentation and files in "Vision" directory to backup what is on the Raspberry Pi 2
- [ ] ~~Fix GRIP so the GRIP SmartDashboard extension can be used instead of a web browser~~
