### ISSUE TITLE
Lidar TODO

### ISSUE THREAD

**Issue by Philanatidae** [FIRST-Team-2557-The-SOTABots/FRC_Robot#6]
These are the items that still need to be finished in order to finish lidar.
- [x] Implement algorithms for looking at angles ahead of the robot
- [ ] ~~Write a plugin for the SmartDashboard to view Lidar distances~~
- [ ] ~~Determine which surfaces the InfraRed laser can bounce off of (what the Lidar can detect)~~
